# Generated by Django 5.2 on 2025-07-19 02:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0002_address_user_address_gallery_permission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('place', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=256)),
                ('address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=256, null=True)),
                ('pincode', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_country', to='core.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_state', to='core.state')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_unisex', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[('AC', 'AC'), ('Non AC', 'Non AC')], max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('trainers', models.ManyToManyField(related_name='branch_trainers', to='user.trainer')),
            ],
            options={
                'verbose_name': 'Branch Settings',
                'verbose_name_plural': 'Branch Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchWorkingTimeAndDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('am_from', models.TimeField(blank=True, null=True)),
                ('am_to', models.TimeField(blank=True, null=True)),
                ('pm_from', models.TimeField(blank=True, null=True)),
                ('pm_to', models.TimeField(blank=True, null=True)),
                ('ladies_time', models.TimeField(blank=True, null=True)),
                ('mixed_time', models.TimeField(blank=True, null=True)),
                ('working_days', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=100)),
                ('is_holidays', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_working_time_and_days', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Working Time and Days',
                'verbose_name_plural': 'Branch Working Time and Days',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gym_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Partnership', 'Partnership'), ('Own', 'Own')], max_length=50)),
                ('owner_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
                'ordering': ['-created_at'],
            },
        ),
    ]
