# Generated by Django 5.2 on 2025-12-14 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_initial'),
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsettings',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='trainers',
            field=models.ManyToManyField(related_name='branch_trainers', to='user.trainer'),
        ),
        migrations.AddField(
            model_name='branchworkingtimeanddays',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_working_time_and_days', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='branchworkingtimeanddays',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_settings_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_settings_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_warehouse', to='organization.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
