# Generated by Django 5.2 on 2025-11-03 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency'),
        ('organization', '0001_initial'),
        ('user', '0002_address_user_address_gallery_permission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='country',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='place',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='build_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='branch',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='webiste',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings_address', to='user.address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('webiste', models.URLField(blank=True, max_length=256, null=True)),
                ('build_date', models.DateTimeField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='branch_settings_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('language', models.CharField(max_length=256)),
                ('owner_type', models.CharField(blank=True, choices=[('Single Owner', 'Single Owner'), ('Multiple Owner', 'Multiple Owner')], max_length=50, null=True)),
                ('gstin_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_settings_address', to='user.address')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company_settings_company', to='organization.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_currency', to='core.currency')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
