# Generated by Django 5.2 on 2025-12-14 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='core.country'),
        ),
        migrations.AddField(
            model_name='state',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_state_in_country'),
        ),
    ]
