# Generated by Django 5.2 on 2025-12-14 00:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_attribute_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_numeric_values', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('line_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('from_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('to_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('increment', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='product.productattributes')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attributes Values',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_category_parent', to='product.productcategory')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_group_product_category', to='accounts.taxgroups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('maintain_stock', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('Moving Average', 'Moving Average')], max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('hsn_code', models.CharField(max_length=256)),
                ('allow_sale', models.BooleanField(default=True)),
                ('allow_purchase', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mop', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_warranty', models.BooleanField(default=False)),
                ('warranty_period', models.PositiveIntegerField(blank=True, null=True)),
                ('barcode_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_barcode', to='core.barcodes')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_brand', to='core.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('default_purchase_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_purchase_uom', to='core.unitofmeasure')),
                ('default_sales_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_sale_uom', to='core.unitofmeasure')),
                ('default_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_uom', to='core.unitofmeasure')),
                ('default_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_warehouse', to='organization.warehouse')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group', to='product.productcategory')),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_tax_group', to='accounts.taxgroups')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variant', to='product.products')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductsBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_bundle_id', models.CharField(max_length=256, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('template_product', models.ForeignKey(limit_choices_to={'allow_sale': True, 'is_template': True}, on_delete=django.db.models.deletion.PROTECT, related_name='template_product', to='product.products')),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_uom', to='core.unitofmeasure')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_product', to='product.products')),
                ('product_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_parent', to='product.productsbundle')),
            ],
            options={
                'verbose_name': 'Product Bundle Item',
                'verbose_name_plural': 'Product Bundle Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUOMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversion_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('from_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_uom', to='core.unitofmeasure')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_uoms', to='product.products')),
                ('to_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_uom', to='core.unitofmeasure')),
            ],
            options={
                'verbose_name': ('Product UOM',),
                'verbose_name_plural': 'Product UOMs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_attribute_branch', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_attribute_company', to='organization.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'is_variant': True}, on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_attributes', to='product.products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['name'], name='product_pro_name_07d794_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['product_id'], name='product_pro_product_5ba6ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='productuoms',
            constraint=models.UniqueConstraint(fields=('product', 'from_uom', 'to_uom'), name='unique_product_uom_conversion'),
        ),
    ]
