# Generated by Django 5.2 on 2026-09-20 11:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_attribute_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_numeric_values', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('line_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('from_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('to_range', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('increment', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attributes Values',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Product Bundle Item',
                'verbose_name_plural': 'Product Bundle Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_category_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('maintain_stock', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('opening_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valuation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('Moving Average', 'Moving Average')], max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('hsn_code', models.CharField(max_length=256)),
                ('allow_sale', models.BooleanField(default=True)),
                ('allow_purchase', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mop', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_warranty', models.BooleanField(default=False)),
                ('warranty_period', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductsBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_bundle_id', models.CharField(max_length=256, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Product Bundle',
                'verbose_name_plural': 'Product Bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUOMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversion_factor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': ('Product UOM',),
                'verbose_name_plural': 'Product UOMs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
