# Generated by Django 5.2 on 2026-09-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('core', '0002_initial'),
        ('organization', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productattributevalues',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productattributevalues',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values', to='product.productattributes'),
        ),
        migrations.AddField(
            model_name='productattributevalues',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbundleitems',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbundleitems',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_uom', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productbundleitems',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_category_parent', to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.taxgroups'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='barcode_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.barcodes'),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='default_purchase_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='products',
            name='default_sales_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='products',
            name='default_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='products',
            name='default_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.warehouse'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_group', to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.taxgroups'),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variant', to='product.products'),
        ),
        migrations.AddField(
            model_name='productbundleitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_product', to='product.products'),
        ),
        migrations.AddField(
            model_name='productsbundle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsbundle',
            name='template_product',
            field=models.ForeignKey(limit_choices_to={'allow_sale': True, 'is_template': True}, on_delete=django.db.models.deletion.PROTECT, related_name='template_product', to='product.products'),
        ),
        migrations.AddField(
            model_name='productsbundle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbundleitems',
            name='product_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bundle_parent', to='product.productsbundle'),
        ),
        migrations.AddField(
            model_name='productuoms',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productuoms',
            name='from_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_uom', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productuoms',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_uoms', to='product.products'),
        ),
        migrations.AddField(
            model_name='productuoms',
            name='to_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_uom', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='productuoms',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_variant': True}, on_delete=django.db.models.deletion.PROTECT, related_name='product_variant_attributes', to='product.products'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['name'], name='product_pro_name_07d794_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['product_id'], name='product_pro_product_5ba6ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='productuoms',
            constraint=models.UniqueConstraint(fields=('product', 'from_uom', 'to_uom'), name='unique_product_uom_conversion'),
        ),
    ]
