# Generated by Django 5.2 on 2025-12-14 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('root_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Account Groups',
                'verbose_name_plural': 'Account Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('sub_type', models.CharField(choices=[('Cash', 'Cash'), ('Accounts Payable', 'Accounts Payable'), ('Accounts Receivable', 'Accounts Receivable'), ('Bank', 'Bank')], max_length=50)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('branch_name', models.CharField(max_length=256)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bank_account_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Currenct', 'Current'), ('Fixed', 'Fixed')], max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('journal_id', models.CharField(max_length=256, unique=True)),
                ('voucher_no', models.CharField(blank=True, max_length=256, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_group_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tax Groups',
                'verbose_name_plural': 'Tax Groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
