# Generated by Django 5.2 on 2025-12-14 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroups',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_group_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_groups_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_groups', to='accounts.accountgroups'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_group', to='accounts.accountgroups'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_bank', to='organization.company'),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tax',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_tax', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='tax',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='tax',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_group_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_tax', to='accounts.tax'),
        ),
    ]
