# Generated by Django 5.2 on 2026-09-20 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
        ('organization', '0001_initial'),
        ('registrations', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroups',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_groups', to='accounts.accountgroups'),
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_group', to='accounts.accountgroups'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_customer', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_supplier', to='registrations.supplier'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccounttype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccounttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_type_account', to='accounts.bankaccounttype'),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.address'),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_branch_bank', to='accounts.bank'),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_bank_branch', to='accounts.bankbranch'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_bank', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_cogs_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_cogs', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_income_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_income', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_round_off_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_round_off', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_stock_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_stock_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_stock_adjustment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_stock_adjustment', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_stock_received_but_not_billed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_stock_receievd_not_billed', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='default_write_off_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_write_off', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='defaultaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='against_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_against_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_ledger_customer', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_ledger_supplier', to='registrations.supplier'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='transaction_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='account_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_journal', to='accounts.journal'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registrations.supplier'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.costcenter'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.project'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='opening_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_invoice_items', to='accounts.openinginvoicecreation'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='registrations.supplier'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tax',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='tax',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='tax',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='tax',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tax',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroupdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroupdetail',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_groups_tax', to='accounts.tax'),
        ),
        migrations.AddField(
            model_name='taxgroupdetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.company'),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroupdetail',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_group_details', to='accounts.taxgroups'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_taxtype', to='accounts.taxtype'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['voucher_no', 'posting_date'], name='accounts_ge_voucher_4aba70_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['account', 'posting_date'], name='accounts_ge_account_b7a941_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['company', 'posting_date'], name='accounts_ge_company_3c624a_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['is_cancelled'], name='accounts_ge_is_canc_fdc32f_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_id'], name='accounts_jo_journal_666bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['posting_date'], name='accounts_jo_posting_4b6b45_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetails',
            index=models.Index(fields=['journal', 'row_index'], name='accounts_jo_journal_554f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetails',
            index=models.Index(fields=['account'], name='accounts_jo_account_70f2df_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetails',
            index=models.Index(fields=['account_currency'], name='accounts_jo_account_184f30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journaldetails',
            unique_together={('journal', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['opening_invoice_id'], name='accounts_op_opening_3041f2_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['invoice_type'], name='accounts_op_invoice_439ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['posting_date'], name='accounts_op_posting_13e317_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['status'], name='accounts_op_status_c45681_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['opening_invoice', 'row_index'], name='accounts_op_opening_fa2a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['customer'], name='accounts_op_custome_d8d845_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['supplier'], name='accounts_op_supplie_b3943a_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['posting_date'], name='accounts_op_posting_db60df_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['due_date'], name='accounts_op_due_dat_2aa613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openinginvoicecreationitems',
            unique_together={('opening_invoice', 'row_index')},
        ),
    ]
