# Generated by Django 5.2 on 2025-12-24 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0003_barcodes_updated_by_brand_updated_by_and_more'),
        ('hr', '0001_initial'),
        ('organization', '0003_branch_updated_by_branchsettings_updated_by_and_more'),
        ('registrations', '0002_remove_customer_address_customer_customer_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gl_id', models.CharField(max_length=256, unique=True)),
                ('voucher_no', models.CharField(db_index=True, max_length=256)),
                ('debit_amount_ac', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount in account currency', max_digits=15)),
                ('credit_amount_ac', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount in account currency', max_digits=15)),
                ('debit_amount_tc', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount in transaction currency', max_digits=15)),
                ('credit_amount_tc', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount in transaction currency', max_digits=15)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Debit amount in base currency', max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Credit amount in base currency', max_digits=15)),
                ('transaction_exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='Exchange rate: Transaction Currency to Base Currency(Company default currency)', max_digits=12)),
                ('account_exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='Exchange rate: Account Currency to Base Currency(Company default currency)', max_digits=12)),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=10, null=True)),
                ('fiscal_period', models.CharField(blank=True, max_length=10, null=True)),
                ('party_type', models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Supplier', 'Supplier')], null=True)),
                ('voucher_type', models.CharField(choices=[('Purchase Invoice', 'Purchase Invoice'), ('Sale Invoice', 'Sale Invoice')], max_length=256)),
                ('voucher_sub_type', models.CharField(blank=True, max_length=256, null=True)),
                ('against_voucher', models.CharField(blank=True, max_length=256, null=True)),
                ('against_voucher_type', models.CharField(blank=True, max_length=256, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'General Ledger Entry',
                'verbose_name_plural': 'General Ledger Entries',
                'ordering': ['-posting_date', '-transaction_datetime'],
            },
        ),
        migrations.CreateModel(
            name='JournalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('row_index', models.PositiveIntegerField()),
                ('party_type', models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Employee', 'Employee')], max_length=20, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate from account currency to company currency', max_digits=15)),
                ('debit_amount_in_company_currency', models.DecimalField(blank=True, decimal_places=5, help_text='Debit amount in company currency', max_digits=15, null=True)),
                ('credit_amount_in_company_currency', models.DecimalField(blank=True, decimal_places=5, help_text='Credit amount in company currency', max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Journal Details',
                'verbose_name_plural': 'Journal Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningInvoiceCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_invoice_id', models.CharField(max_length=256, unique=True)),
                ('posting_date', models.DateTimeField()),
                ('invoice_type', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Service', 'Service')], max_length=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Opening Invoice Creation',
                'verbose_name_plural': 'Opening Invoice Creations',
                'ordering': ['-posting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningInvoiceCreationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Original invoice number from previous system', max_length=256, null=True)),
                ('posting_date', models.DateField()),
                ('due_date', models.DateField()),
                ('item_name', models.CharField(default='Opening Invoice', max_length=256)),
                ('outstanding_amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('row_index', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Opening Invoice Creation Items',
                'verbose_name_plural': 'Opening Invoice Creation Items',
                'ordering': ['opening_invoice', 'row_index'],
            },
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='voucher_no',
            new_name='reference_number',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='debit_amount',
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='journal_branch', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='journal_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='difference_amount',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Exchange gain/loss amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(choices=[('Journal Entry', 'Journal Entry'), ('Bank Entry', 'Bank Entry'), ('Cash Entry', 'Cash Entry'), ('Opening Entry', 'Opening Entry')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_opening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='multi_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='posting_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='reference_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total credit in transaction currency', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='total_credit_in_company_currency',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Total credit in company currency', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='total_debit_amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total debit in transaction currency', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='total_debit_in_company_currency',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Total debit in company currency', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tax',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxgroups',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_id'], name='accounts_jo_journal_666bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['posting_date'], name='accounts_jo_posting_4b6b45_idx'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries_account', to='core.currency'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='against_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_against_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_customer', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_supplier', to='registrations.supplier'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='transaction_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries_transaction', to='core.currency'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_account', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='account_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of the account being debited/credited', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_currency', to='core.currency'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_customer', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_employee', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_journal', to='accounts.journal'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_details_supplier', to='registrations.supplier'),
        ),
        migrations.AddField(
            model_name='journaldetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_invoice_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_invoice_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_invoice_cost_center', to='organization.costcenter'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_invoice_project', to='organization.project'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_invoice_customer', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='opening_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_invoice_items', to='accounts.openinginvoicecreation'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_invoice_supplier', to='registrations.customer'),
        ),
        migrations.AddField(
            model_name='openinginvoicecreationitems',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['voucher_no', 'posting_date'], name='accounts_ge_voucher_4aba70_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['account', 'posting_date'], name='accounts_ge_account_b7a941_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['company', 'posting_date'], name='accounts_ge_company_3c624a_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['is_cancelled'], name='accounts_ge_is_canc_fdc32f_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetails',
            index=models.Index(fields=['journal', 'row_index'], name='accounts_jo_journal_554f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetails',
            index=models.Index(fields=['account'], name='accounts_jo_account_70f2df_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetails',
            index=models.Index(fields=['account_currency'], name='accounts_jo_account_184f30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journaldetails',
            unique_together={('journal', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['opening_invoice_id'], name='accounts_op_opening_3041f2_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['invoice_type'], name='accounts_op_invoice_439ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['posting_date'], name='accounts_op_posting_13e317_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreation',
            index=models.Index(fields=['status'], name='accounts_op_status_c45681_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['opening_invoice', 'row_index'], name='accounts_op_opening_fa2a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['customer'], name='accounts_op_custome_d8d845_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['supplier'], name='accounts_op_supplie_b3943a_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['posting_date'], name='accounts_op_posting_db60df_idx'),
        ),
        migrations.AddIndex(
            model_name='openinginvoicecreationitems',
            index=models.Index(fields=['due_date'], name='accounts_op_due_dat_2aa613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openinginvoicecreationitems',
            unique_together={('opening_invoice', 'row_index')},
        ),
    ]
