# Generated by Django 5.2 on 2026-05-19 02:04

import core.formatchecker
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diet_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('descritpion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Diet')),
                ('diet_type', models.CharField(choices=[('Keto', 'Keto'), ('Vegetarian', 'Vegetarian'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('goal_type', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain')], max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('calorie_range', models.IntegerField(blank=True, null=True)),
                ('company', models.PositiveBigIntegerField()),
                ('branch', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Diet',
                'verbose_name_plural': 'Diets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_category_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('playlist_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('platform', models.CharField(blank=True, help_text='Spofity, Youtube, etc.', max_length=50, null=True)),
                ('decsription', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Playlist')),
                ('branch', models.PositiveBigIntegerField()),
                ('company', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workout_id', models.CharField(max_length=256, unique=True)),
                ('body_part', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Leg', 'Leg'), ('Shoulder', 'Shoulder'), ('Triceps', 'Triceps'), ('Glutes', 'Glutes'), ('Biceps', 'Biceps'), ('Calf', 'Calf')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('image', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('reps', models.IntegerField(default=15)),
                ('sets', models.IntegerField(default=3)),
                ('branch', models.PositiveBigIntegerField()),
                ('company', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_uom', to='core.unitofmeasure')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_categorys', to='fitness.itemcategory')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemMacros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_macros_id', models.CharField(max_length=256, unique=True)),
                ('protein', models.PositiveIntegerField(default=0)),
                ('fat', models.PositiveIntegerField(default=0)),
                ('carbs', models.PositiveIntegerField(default=0)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('sugar', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_macros', to='fitness.item')),
            ],
            options={
                'verbose_name': 'Item Macros',
                'verbose_name_plural': 'Item Macros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('songs', core.formatchecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='songs/')),
                ('title', models.CharField(max_length=256)),
                ('playlist_url', models.URLField(blank=True, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_songs', to='fitness.playlist')),
            ],
            options={
                'verbose_name': 'Playlist Song',
                'verbose_name_plural': 'Playlist Songs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workout_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('branch', models.PositiveBigIntegerField()),
                ('company', models.PositiveBigIntegerField()),
                ('excersises', models.ManyToManyField(related_name='workouts_plan', to='fitness.workouts')),
            ],
            options={
                'verbose_name': 'Workouts Plan',
                'verbose_name_plural': 'Workout Plans',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diet_day', models.CharField(help_text='like day1, day2, etc', max_length=256)),
                ('part_of_day', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Before Workout', 'Before Workout'), ('After Workout', 'After Workout'), ('Supper', 'Supper')], max_length=20)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diet_diet_details', to='fitness.diet')),
                ('food_items', models.ManyToManyField(related_name='food_items', to='fitness.item')),
            ],
            options={
                'verbose_name': 'Diet Detail',
                'verbose_name_plural': 'Diet Details',
                'ordering': ['created_at'],
                'unique_together': {('diet', 'diet_day', 'part_of_day')},
            },
        ),
    ]
