# Generated by Django 5.2 on 2025-11-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        ('organization', '0002_remove_branch_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='diet_plan_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='item_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='item_category_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item_category_id',
            field=models.CharField(default=1, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmacros',
            name='item_macros_id',
            field=models.CharField(default=1, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='playlist_branch', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='playlist_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='uom_id',
            field=models.CharField(default=1, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workouts_branch', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workouts_company', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsplan',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workout_plan_branch', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsplan',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workout_plan_company', to='organization.company'),
            preserve_default=False,
        ),
    ]
