# Generated by Django 5.2 on 2025-12-14 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('fitness', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diet_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='diet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diet_plan_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='diet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietdetail',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diet_diet_details', to='fitness.diet'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_uom', to='core.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='dietdetail',
            name='food_items',
            field=models.ManyToManyField(related_name='food_items', to='fitness.item'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_categorys', to='fitness.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemmacros',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemmacros',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_macros', to='fitness.item'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistsongs',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_songs', to='fitness.playlist'),
        ),
        migrations.AddField(
            model_name='workouts',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workouts_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='workouts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workouts_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='workouts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutsplan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_plan_branch', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='workoutsplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_plan_company', to='organization.company'),
        ),
        migrations.AddField(
            model_name='workoutsplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutsplan',
            name='excersises',
            field=models.ManyToManyField(related_name='workouts_plan', to='fitness.workouts'),
        ),
        migrations.AlterUniqueTogether(
            name='dietdetail',
            unique_together={('diet', 'diet_day', 'part_of_day')},
        ),
    ]
