# Generated by Django 5.2 on 2026-09-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_group_id', models.CharField(max_length=256, unique=True)),
                ('group_name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_id', models.CharField(max_length=128, unique=True)),
                ('supplier_name', models.CharField(max_length=256)),
                ('alias', models.CharField(blank=True, max_length=120, null=True)),
                ('supplier_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Partnership', 'Partnership')], max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_group_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Supplier Group',
                'verbose_name_plural': 'Supplier Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_id', models.CharField(max_length=256, unique=True)),
                ('customer_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Partnership', 'Partnership')], max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=15, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.accounts')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
