# Generated by Django 5.2 on 2026-05-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_id', models.CharField(max_length=256, unique=True)),
                ('customer_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_group', models.PositiveBigIntegerField()),
                ('tax_group', models.PositiveBigIntegerField(blank=True, null=True)),
                ('account', models.PositiveBigIntegerField()),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Partnership', 'Partnership')], max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('shipping_address', models.PositiveBigIntegerField()),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_group_id', models.CharField(max_length=256, unique=True)),
                ('group_name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('company', models.PositiveBigIntegerField()),
                ('branch', models.PositiveBigIntegerField()),
                ('tax_group', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
