# Generated by Django 5.2 on 2026-05-19 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photos', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallerys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=256, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/profile/')),
                ('userr_type', models.CharField(choices=[('Admin', 'Admin'), ('Branch Admin', 'Branch Admin'), ('Trainer', 'Trainer'), ('Member', 'Member')], max_length=20)),
                ('is_trainer', models.BooleanField(default=False)),
                ('height', models.CharField(blank=True, max_length=256, null=True)),
                ('weight', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.PositiveBigIntegerField(blank=True, null=True)),
                ('branch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(help_text='For naming the address like head office or home address.', max_length=256)),
                ('address_type', models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Home', 'Home'), ('Warehouse', 'Warehouse')], max_length=50, null=True)),
                ('address_line_1', models.CharField(max_length=256)),
                ('address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.PositiveBigIntegerField()),
                ('state', models.PositiveBigIntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_address', to='user.address'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('descritpiton', models.CharField(blank=True, max_length=256, null=True)),
                ('permission', models.ManyToManyField(related_name='role', to='user.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='user_role', to='user.role'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('PT', 'Personal Trainer'), ('All', 'All Rounder'), ('AT', 'Athletic Trainer')], max_length=20)),
                ('certifiation', models.FileField(upload_to='trainer_cerfificates/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_leave', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer',
                'verbose_name_plural': 'Trainers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_gallery', to='user.gallery')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='user.userprofile'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_id', models.CharField(max_length=256, unique=True)),
                ('attendence_for', models.CharField(choices=[('Trainer', 'Trainer'), ('Member', 'Member')], max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_attend_user_id_fb8535_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('login_log_id', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='login_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_loginl_user_id_9c3da4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_userpr_user_id_d39789_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['user'], name='user_galler_user_id_67ee65_idx'),
        ),
    ]
