# Generated by Django 5.2 on 2025-11-03 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_currency'),
        ('organization', '0002_remove_branch_address_line_and_more'),
        ('user', '0002_address_user_address_gallery_permission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Head Office', 'Head Office'), ('Billing', 'Billing'), ('Shipping', 'Shipping'), ('Home', 'Home')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='address_country', to='core.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=1, help_text='For naming the address like head office or home address.', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='address_state', to='core.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='branch_user', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to='organization.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile_gallery', to='user.gallery'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['content_type', 'object_id'], name='user_addres_content_7d9387_idx'),
        ),
    ]
